server:
  port: 8080
spring:
  banner:
    location: classpath:banner/banner.txt
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
  datasource:
      name: datasource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/projectTodo?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      hikari:
        auto-commit: true
        minimum-idle: 5
        maximum-pool-size: 15
        idle-timeout: 30000
        pool-name: hikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
pagehelper:
  helper-dialect: mysql
